### PR TITLE
correct log output

### PR DESCRIPTION
**Pull request by da-kami**
ERC20 in log was wrong. 
Made messages similar.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
bors retry

**Comment by thomaseizinger** [comment]
bors retry

**Comment by D4nte** [comment]
> 🔒 Permission denied
> 
> Existing reviewers: [click here to make mergify[bot] a reviewer](https://app.bors.tech/repositories/21096/add-reviewer/mergify%5Bbot%5D)

@thomaseizinger is that fixed too?

**Comment by thomaseizinger** [comment]
> > lock Permission denied
> > Existing reviewers: [click here to make mergify[bot] a reviewer](https://app.bors.tech/repositories/21096/add-reviewer/mergify%5Bbot%5D)
> 
> @thomaseizinger is that fixed too?

yes!

**Pull request merged**
